---
# Composer wants to run as a non-privleged user.     
- name: Add composer user 
  user:
    name: composer
    state: present

- name: Ensure /tmp/downloads exists
  file:
    path: /tmp/downloads
    owner: root
    group: wheel
    state: directory

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/downloads/composer-installer.php
    mode: 0775

- name: Install Composer
  become: yes
  become_user: composer
  command: >
    php /tmp/downloads/composer-installer.php
  args:
    chdir: /opt/wpn/bin
    creates: /opt/wpn/bin/composer.phar

- name: Make sure Composer is executable
  file:
    path: /opt/wpn/bin/composer.phar
    owner: composer
    group: wheel
    mode: 0775
