---

- name: Make Red Hat PHP7 our PHP of choice
  alternatives:
    name: php
    link: /usr/bin/php
    path: /opt/rh/rh-php71/root/bin/php
    priority: 1

- name: Set upload_max_filesize
  replace:
    dest: /etc/opt/rh/rh-php71/php.ini
    regexp: >
      ^upload_max_filesize = 2M$
    replace: "upload_max_filesize = {{ wpn_upload_max_filesize }}"

- name: Set post_max_size
  replace:
    dest: /etc/opt/rh/rh-php71/php.ini
    regexp: >
      ^post_max_size = 8M$
    replace: "post_max_size = {{ wpn_post_max_size }}"

- name: Set php.ini memory_limit
  replace:
    dest: /etc/opt/rh/rh-php71/php.ini
    regexp: >
      ^memory_limit = .*$
    replace: "memory_limit = {{ wpn_memory_limit }}"
    
- name: Set PHP timezone
  replace:
    dest: /etc/opt/rh/rh-php71/php.ini
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = {{ wpn_default_timezone }}"

- name: Set PHP CURLOPT_CAINFO
  replace:
    dest: /etc/opt/rh/rh-php71/php.ini
    regexp: >
      ^;curl.cainfo=$
    replace: "curl.cainfo = /etc/pki/tls/certs/ca-bundle.crt"

- name: Configure PHP-FPM max_children
  replace:
    dest: /etc/opt/rh/rh-php71/php-fpm.d/www.conf
    regexp: >
      ^pm\.max_children = 50$
    replace: "pm.max_children = 256"

- name: Configure PHP-FPM pm.start_servers
  replace:
    dest: /etc/opt/rh/rh-php71/php-fpm.d/www.conf
    regexp: >
      ^pm\.start_servers = 5$
    replace: "pm.start_servers = 180"

- name: Configure PHP-FPM pm.min_spare_servers
  replace:
    dest: /etc/opt/rh/rh-php71/php-fpm.d/www.conf
    regexp: >
      ^pm\.min_spare_servers = 5$
    replace: "pm.min_spare_servers = 32"

- name: Configure PHP-FPM pm.max_spare_servers
  replace:
    dest: /etc/opt/rh/rh-php71/php-fpm.d/www.conf
    regexp: >
      ^pm\.max_spare_servers = 35$
    replace: "pm.max_spare_servers = 196"

- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
    - httpd_can_network_connect
    - httpd_can_sendmail
  tags: selinux

- name: Allow apache group to view httpd log files
  file:
    path: "{{ httpd_log_dir }}"
    owner: root
    group: apache
    mode: 0750

- name: Add /srv config include to http.conf
  lineinfile:
    state: present
    dest: "{{ httpd_etc_dir }}/conf/httpd.conf"
    line: "IncludeOptional \"/srv/*/etc/*.conf\""

- name: Ensure /etc/profile.d/wpn-ops.sh exists
  file:
    path: /etc/profile.d/wpn-ops.sh
    state: touch
    mode: 0644
    owner: root
    group: root

- name: Add ops scripts to path
  lineinfile:
    state: present
    dest: /etc/profile.d/wpn-ops.sh
    line: "export PATH=/opt/wpn/bin:$PATH"
